services:
  traefik:
    container_name: traefik
    image: traefik:v3.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=frontend"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

  backend:
    container_name: backend
    build: ./src/backend
    env_file:
      - .env
    labels:
      traefik.http.routers.backend.rule: "Host(`api.localhost`)"
      traefik.http.routers.backend.entrypoints: "websecure"
    depends_on:
      - redis
      - postgres
    networks:
      - frontend
      - backend

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.29
    environment:
      - MP_SMTP_BIND_ADDR=0.0.0.0:1025
      - MP_UI_BIND_ADDR=0.0.0.0:8025
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer:5.4.2-standalone
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - backend

networks:
  frontend:
    name: frontend
  backend:
    name: backend

volumes:
  redis-data:
  postgres-data: