services:
  backend:
    container_name: backend
    build: ./src/backend
    env_file:
      - .env
    labels:
      traefik.http.routers.backend.rule: "Host(`localhost`)"
    depends_on :
      - redis
      - postgres

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.29
    environment:
      - MP_SMTP_BIND_ADDR=0.0.0.0:1025
      - MP_UI_BIND_ADDR=0.0.0.0:8025
      
  redis:
    container_name: redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:5.4.2-standalone
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  traefik:
    container_name: traefik
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  redis-data:
  postgres-data: