http:
  middlewares:
    compress:
      compress: {}

    secure:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "no-referrer"
        forceSTSHeader: true
        stsSeconds: 15552000
        stsIncludeSubdomains: true
        stsPreload: true

    api-ratelimit:
      rateLimit:
        average: 100
        burst: 50
